name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [javascript] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: ${{ matrix.language }}
